version: '2'
services:
  puppet:
    build: puppetmaster
    ports:
      - "8140:8140"
    volumes:
      - ./puppetmaster/conf:/etc/puppet
      - ./puppetmaster/var:/var/lib/puppet
  puppetdb:
    build: puppetdb
    volumes:
      - ./puppetdb/conf:/etc/puppetdb
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: puppetdb
      POSTGRES_PASSWORD: dbpasswd
