version: '2'
volumes:
  puppetmaster:
  puppetdb:
services:
  puppetmaster:
    build: puppetmaster
    ports:
      - "8140:8140"
    volumes:
      - ./puppetmaster/conf:/etc/puppet
      - ./puppetmaster/var:/var/lib/puppet
  puppetdb:
    build: puppetdb
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./puppetdb/conf:/etc/puppetdb
